---
# Example from https://joss.readthedocs.io/en/latest/submitting.html
title: 'ManyEcoEvo: an R package for working with the "Same Data, Different Analysts" Project in Ecology and Evolutionary Biology, and other many-analyst style data'
tags:
  - R
  - meta-analysis
  - metaresearch
  - ecology
  - evolutionary biology
  - many-analysts
authors:
  - name: Elliot Gould
    orcid: 0000-0003-0872-7098
    affiliation: "1" 
  - name: Hannah S. Fraser
    orcid: 0000-0000-0000-0000
    affiliation: "1"
  - name: Shinichi Nakagawa
    orcid: 0000-0000-0000-0000
    affiliation: "2"
  - name: Timothy H. Parker
    orcid: 0000-0000-0000-0000
    affiliation: "3"
affiliations:
 - name: The University of Melbourne
   index: 1
 - name: The University of New South Wales
   index: 2
 - name: Whitman College
   index: 3
citation_author: Gould and Fraser et al. 
date: "`r Sys.Date()`"
year: 2023
bibliography: paper.bib
output: 
  # word_document: default
  rticles::joss_article:
    journal: JOSS
csl: apa.csl
---

# Summary

Many-analyst studies are a format of crowd-sourced scientific analysis [@schweinsberg2021], where analysts simultaneously, but independently, research the same research question, using the same dataset [@Voracek2019; @silberzahn2018].
Many-analyst studies demonstrate how subjective, often arbitrary and usually defensible analysis decisions may influence research results [@silberzahn2018] due to either disagreement among researchers or due to analytic uncertainty about choices such as which observations to include and what data-analysis strategy is most appropriate [@Voracek2019].
Managing the analysis pipeline of such data is complex and is better implemented with dedicated software.

Typical scientific approaches proceed with a single team, and one analytic specification, or at most several specifications implemented.
Thus the effect of alternative defensible analytic choices that could have been implemented is never known, either because alternative specifications aren't explored, or worse, because analysts / authors implement them but do not publish alternative analysis specifications.
However, we know from simulations and case studies that researcher degrees of freedom can result in spurious findings [@simmons2011], and these researcher degrees of freedom are susceptible to publication bias, p-hacking and other questionable research practice.
Similarly, specification curve analysis of published findings have demonstrated that the published conclusion had empirical support from only a small sample of the overall plausible specifications (evidence of spurious findings, and possibly publication bias and p-hacking) [@Simonsohn2019].
These types of studies are growing in popularity, as we explain below.

*ManyEcoEvo* is an R package [@RCoreTeam2022] designed to *facilitate the analysis of* a many-analyst study in ecology and evolutionary biology, the *ManyEcoEvo Project* [@gould2023].
The purpose of *ManyEcoEvo* is to reproducibly implement the analysis and presentation of results for Gould *et al.* [-@gould2023] such that the 246 analysts as well as other interested researchers may independently reproduce the study's findings.
The package also aims to facilitate re-analyses and replications of Gould *et al.* [-@gould2023], as well as facilitating the analysis of similar many-analyst style datasets.

The ManyEcoEvo project is a many-analyst study that aimed to empirically explore the variation in effect sizes and model predictions generated by analytical decisions of different researchers within ecology and evolutionary biology [@gould2023].
174 analyst teams, comprising 246 analysts, independently investigated the answers to two pre-specified research questions using two previously unpublished datasets, one from conservation ecology, and one from evolutionary biology.
Analysts investigating the evolutionary biology dataset examined the effect of sibling number and nestling growth of blue tits (*Cyanistes caeruleus*), while analysts investigating the conservation ecology dataset examined the relationship between grass cover and *Eucalyptus* tree seedling recruitment.
The ManyEcoEvo project quantified the variation in results among analyses using meta-analysis and additionally sought to understand how features of studies such as, variable selection, random effects structures, qualitative and numeric ratings of the methods by peer-reviewers, influenced deviation from the meta-analytic mean.

All raw data sets and metadata provided to independent teams for analysis are publicly archived at <https://osf.io/qjzby> and <https://osf.io/hdv8m>, respectively.
Analyst survey responses and results are provided in the package GitHub repository (<https://github.com/egouldo/ManyEcoEvo/>), which is also archived on Zenodo (<https://doi.org/10.5281/zenodo.10046153>).
*ManyEcoEvo* contains tools for data-cleaning and processing tasks encountered when working with with many-analyst style data, functions for implementing and reproducing the analysis described inGould *et al.* [-@gould2023], establishes a structured workflow that facilitates re-analyses and replications of Gould *et al.* [-@gould2023] as well as implementation for new many-analyst studies, including a planned extension of the ManyEcoEvo project.

# Statement of Need

The last ten years has seen the growing emergence of many-analyst projects, [e.g. @silberzahn2018; @botvinik-nezer2020; @huntington-klein2021; @schweinsberg2021; @breznau2022; @hoogeveen2022many; @coretta2023], predominantly in the disciplines of psychology and social and behavioural sciences, however we expect more of these types of studies to be published into the near future across other disciplines.
Moreover, collaborative and distributed big team open science projects are becoming increasingly common in ecology and evolutionary biology (e.g. NutNet/DragNet [nutnet.org/index.php/](https://nutnet.org/index.php/){.uri}, ManyBirds [themanybirds.com](http://themanybirds.com){.uri}) as well as other disciplines [ManyBabies @ManyBabies , ManyPrimates @ManyPrimates] which pose computationally analogous data-manipulation and analysis problems to the many-analyst workflow addressed by the *ManyEcoEvo* approach.

The *ManyEcoEvo* package was created to implement the analysis for the 'Same Data, Many Analysts in Ecology and Evolutionary Biology' project [@gould2023] and to allow the 246 co-authors and other interested researchers to computationally reproduce our analysis.
Following [@Marwick2018], [@Vuorre2021] and [@Filazzola2022], we opted to develop this research compendium as an R package as we find it best encapsulates the principles of 'clean code' for effective communication of the science, and therefore facilitates future reproduction, replication and potential synthesis [R packages as research compendia].
*ManyEcoEvo* was designed for the ManyEcoEvo project, the structured approach it employs establishes a workflow that can be generalised and applied to new many-analyst style data, facilitating replication of Gould *et al.* [-@gould2023], in addition to computational reproduction [@Stoudt2021], as well as new analyses of many-analyst type studies.

The results of some many-analyst studies have been controversial, yielding re-analyses criticising the original implementation of some many-analyst studies.
For example, [@Auspurg2021] re-analysed part of the seminal 'Red-Card' many-analyst study examining the influence of whether referees were more likely to give red cards to soccer players with dark skin tone than those with light skin tone [@silberzahn2018].
By providing the code and data for Gould *et al.* [-@gould2023] the *ManyEcoEvo* package, we aim to facilitate computational reproductions by others in order to verify our results.
We also aim to facilitate analytic reproductions of this study, wherein *ManyEcoEvo* can be used to re-run the analysis in Gould *et al.* [-@gould2023] with slightly different methods, or subsets of data in order to verify and examine the robustness of our findings.

We are not aware of any R packages or software in other languages exclusively focussed on facilitating many-analyst style studies.
Existing many-analyst code if shared, is written as R scripts particular to that study's analysis (e.g. <https://github.com/manybabies/mb1-analysis-public>, <https://github.com/many-speech-analyses/many_analyses>).
However, there are a range of existing packages with select functionality that addresses various components of many-analyst style analyses, namely meta-analysis, its associated preparation and visualisation, as well as the visualisation component of specification curve analysis / multiverse analysis [@Simonsohn2020; @Steegen2016].
Following the collection of results from teams conducting independent analyses, the data must be 1.
cleaned and prepared for 2.
meta-analysis and other model analysis, which is then 3.
subjected to model checking, statistic extraction and visualisation [@aczel2021].

We provide a suite of miscellaneous functions for data cleaning and processing tasks that we expect to be common to the sorts of data collected by many-analyst style studies.
This was the most time and effort-intensive aspect of the analysis in Gould *et al.* [-@gould2023], and we hope these functions will ease the burden on future researchers conducting many-analyst studies.

*ManyEcoEvo* provides custom functions to calculate standardize effect sizes in the form of Fishers' Z correlation scores in preparation for meta-analysis.
While some existing functions exist within other packages [e.g. `DescTools::FishersZ()` @DescTools, `DiagTest3Grp::FisherZ.var()` @luo2012diagtest3grp], the method for calculating variance of the standardized effect size in Gould *et al.* [-@gould2023] differed slightly, and we wished to avoid reliance on too many external packages [@wickham2023r, Chapter 10.1].
Should *ManyEcoEvo* users wish to deviate from the effect-size standardisation method used in Gould *et al.* [-@gould2023], they are free to use their own functions provided by other software or custom functions [@harrer2021, see chapter 3 for a range of R code to calculate various effect sizes].

`metafor` [@Viechtbauer:2010ks; @Viechtbauer2017] and `meta` [@Balduzzi2019] R packages are the two most commonly used softwares for undertaking meta-analysis in R [@lortie2020].
We provide functions for fitting the exact meta-analysis models used in Gould *et al.* [-@gould2023], which were implemented with the *metafor* package [@Viechtbauer2017], however *ManyEcoEvo* users are free to supply alternative model-fitting functions should they wish to deviate from these specified models.
After model-fitting and analysis, model checking and extraction of model fit and heterogeneity statistics is implemented using a range of existing packages, including: `performance::` [@ludecke2021], `broom.mixed::` [@Bolker2022], `metafor::` [@Viechtbauer2017].
*ManyEcoEvo* also draws on existing visualisation packages to implement forest plots [`ggforestplot::`, @ggforestplot; @orchaRd], funnel plots [`metafor::` @Viechtbauer2017], and specification curve analysis plots [`specr::` @Masur2020 ] to examine the influence of analysis specifications on variation in analysis outcomes.
Select functions from the above packages have been thoughtfully abstracted and coded into wrapper functions according to a principled and structured workflow (described below) for ease of application and generalisation to alternative datasets.

# Same Data, Different Analysts: variation in effect sizes due to analytical decisions in ecology and evolutionary biology

This is the body of the manuscript that will provide a short example of the claims about functionality I've made in the previous sections using the ManyEcoEvo analysis pipeline for correlation coefficients.

# Acknowledgements

We acknowledge the contributions of all 246 analysts and co-authors of Gould *et al. [-@gould2023]* please see the original manuscript for a full list of contributors to the ManyEcoEvo project.

EG is supported by an Australian Government Research Training Program Scholarship.

-   [ ] HF?
-   [ ] SN?
-   [ ] TP?

# References
