#' Compute meta-analysis inputs for a nested-dataframe containing different datasets/subsets of analyst data
#' @description Computes the sorensen diversity indices and joins it to the prepared data in preparation for meta-analysing all subsets of data with `meta_analyse_datasets()`.
#'
#' @param ManyEcoEvo A dataframe grouped by the character columns `dataset`, `estimate_type`, `exclusion_set`. Each group corresponds to a subset of the full `dataset`, and has the subset analyst data  stored in `data`, with its corresponding subset `diversity_data`.
#' @param estimate_type character string, one of "Zr", "yi", "y25", "y50", "y75".
#' @details The name of the subset is derived from the funs generated by `subset_fns_yi` and/or `subset_fns_Zr`.
#'
#' Computes sorensen diversity indices `diversity_indices` for each subset of data returning them in the list-columns `diversity_indices` and joins them to the subset analyst `data`, returning it in the list-column `effects_analysis`.
#'
#' @return A dataframe that includes the additional columns in `ManyEcoEvo`, but with added columns `diversity_indices` and `effects_analysis`.
#' @export
#' @family Multi-dataset Wrapper Functions
compute_MA_inputs <- function(ManyEcoEvo, estimate_type = NULL) {
  # TODO should be renamed something to do with diversity indices... that's the
  # only thing happening here!!
  match.arg(estimate_type, choices = c("Zr", "yi", "y50", "y75", "y25", NULL), several.ok = FALSE)
  # TODO insert check to ensure that if estimate_type supplied, there is NO col with estiamte_type in ManyEcoEvo?
  if (!rlang::is_null(estimate_type)) {
    df <- ManyEcoEvo %>%
      mutate(
        diversity_indices = map(diversity_data, apply_sorensen_calc),
        effects_analysis = map2(
          .x = data, .y = diversity_indices, # TODO post-dev, remove data/diversity_data cols??
          .f = ~ left_join(.x, .y) %>%
            rename(study_id = id_col) %>%
            mutate(estimate_type = !!{{ estimate_type }})
        )
      ) %>% #
      dplyr::group_by(exclusion_set, dataset, estimate_type)
  } else {
    df <- ManyEcoEvo %>%
      pointblank::col_exists("estimate_type") %>%
      mutate(
        diversity_indices = map(diversity_data, apply_sorensen_calc),
        effects_analysis = pmap(
          .l = list(data, diversity_indices, estimate_type),
          .f = ~ left_join(..1, ..2) %>%
            rename(study_id = id_col) %>%
            mutate(estimate_type = ..3)
        )
      ) %>% # TODO can we remove estimate type from this df?
      dplyr::group_by(exclusion_set, dataset, estimate_type)
  }

  return(df)
}
