#' Prepare ManyEcoEvo raw dataset
#'
#' @param master_data_raw Raw data for both eucalyptus and blue tit analyses
#' @param master_raw_metadata Metadata describing `master_data_raw`
#' @param all_review_data Review data for all `dataset`s contained in `master_data_raw`, generated by `prepare_review_data`.
#'
#' @return A tibble of ManyEcoEvo analyst response data for effect-sizes ($Z_r$).
#' @export
#' @family Multi-dataset Wrapper Functions
#' @family targets-pipeline functions
prepare_ManyEcoEvo <- function(master_data_raw,
                               master_raw_metadata,
                               all_review_data) {
  # TODO diff nrow() between master_data_raw And diversity_index_data_raw
  diversity_data_raw <- master_data_raw %>%
    prepare_diversity_raw(., master_raw_metadata)

  ManyEcoEvo <- master_data_raw %>%
    dplyr::select(
      response_id,
      submission_id,
      analysis_id,
      split_id,
      TeamIdentifier,
      id_col,
      beta_estimate,
      contrast,
      adjusted_df,
      beta_SE,
      transformation, # TODO doublecheck this of renamed var and do we need it for this analysis??
      link_function_reported,
      dataset,
      mixed_model,
      # file_name,
      # file_id,
      response_transformation_description,
      response_transformation_status,
      response_variable_type,
      response_construction_description,
      response_variable_name,
      response_id_S2,
      test_variable,
      sample_size,
      Bayesian,
      linear_model,
      model_subclass,
      num_variables,
      num_effects,
      num_fixed_variables,
      num_fixed_effects,
      num_random_variables,
      num_random_effects,
      num_interactions,
      num_duplicate_terms,
      exclusions_all,
      exclusions_effect_analysis,
      exclusion_predictions,
      Conclusion
    ) %>%
    dplyr::left_join(all_review_data)

  ManyEcoEvo <-
    ManyEcoEvo %>%
    dplyr::group_by(dataset) %>%
    dplyr::nest_by(.keep = TRUE) %>%
    dplyr::left_join(diversity_data_raw, by = "dataset") %>%
    tidyr::hoist(data) %>%
    dplyr::mutate(estimate_type = "Zr")

  return(ManyEcoEvo)
}
